// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type UserRes struct {
	Id string `json:"id"`
}

type UserResq struct {
	Id    string `json:"id"`
	Name  string `json:"name"`
	Phone string `json:"phone"`
}
